MAISTRA-1294 Document ServiceMeshMember in Maistra docs
Maistra/maistra.github.io pull request #112
Opened 2020-03-23 15:36 UTC by luksa

2020-03-25 13:22 UTC, dgn approved these changes
lgtm, just minor comments

2020-03-25 13:22 UTC, dgn commented on topics/docs/installation/configuring-members.adoc
> +This resource must be created in the same project as the `ServicemeshControlPlane` resource
typo: Service**M**eshControlPlane (I know you copy-pasted this, but still ;) )

2020-03-25 13:22 UTC, dgn commented on topics/docs/installation/configuring-members.adoc
> +causes the namespace to be added to the `ServiceMeshMemberRoll`.
maybe add "...that resides in the same namespace as the referenced ServiceMeshControlPlane"?

2020-03-25 13:22 UTC, dgn commented on topics/docs/installation/configuring-members.adoc
> +The `RoleBinding` is created by the operator after the administrator creates the
let's call it `Maistra operator` to avoid confusion

2020-03-25 13:43 UTC, luksa commented on topics/docs/installation/configuring-members.adoc
> +This resource must be created in the same project as the `ServicemeshControlPlane` resource
Fixed. Thanks. :)

2020-03-25 13:45 UTC, luksa commented on topics/docs/installation/configuring-members.adoc
> +causes the namespace to be added to the `ServiceMeshMemberRoll`.
Fixed. I've also changed "namespace" to "project".

2020-03-25 13:45 UTC, luksa commented on topics/docs/installation/configuring-members.adoc
> +The `RoleBinding` is created by the operator after the administrator creates the
Done!

2020-03-31 23:49 UTC, knrc requested changes
I've made some suggestions for changes, please feel free to ignore if you disagree with them.

2020-03-31 23:49 UTC, knrc commented on topics/docs/installation/configuring-members.adoc
> +and must be named default. An example resource can be seen below:
Perhaps use `default` to highlight?

2020-03-31 23:49 UTC, knrc commented on topics/docs/installation/configuring-members.adoc
> +
Rewording, perhaps "When the `ServiceMeshMember` is created it will cause the project to be added to the `ServiceMeshMemberRoll` within the control plane project it references."

2020-03-31 23:49 UTC, knrc commented on topics/docs/installation/configuring-members.adoc
> +`mesh-users` `RoleBinding` in the control plane project.
Rewording, perhaps: "This is done by modifying the `mesh-users` `RoleBinding` in the control plane project to enable the RBAC roles and users which should be granted access."

2020-03-31 23:49 UTC, knrc commented on topics/docs/installation/configuring-members.adoc
> +and must be named default. An example resource can be seen below:
It looks as if this is a C&P so up to you whether it should be changed

2020-04-01 12:55 UTC, luksa commented on topics/docs/installation/configuring-members.adoc
> +and must be named default. An example resource can be seen below:
Fixed.

2020-04-01 12:55 UTC, luksa commented on topics/docs/installation/configuring-members.adoc
> +
Fixed.

2020-04-01 12:56 UTC, luksa commented on topics/docs/installation/configuring-members.adoc
> +`mesh-users` `RoleBinding` in the control plane project.
Fixed, but slightly differently from what you suggested. Please review again.

2020-04-01 13:22 UTC, knrc approved these changes

2020-04-01 16:15 UTC, brian-avery commented on topics/docs/installation/installation-options.adoc
> +weight: 5
I feel like this should still be at weight 3. Installing your control plane.... here are your other installation options.

2020-04-01 16:17 UTC, brian-avery commented on topics/docs/installation/automatic-injection.adoc
> -weight: 3
Can we change this title to "Adding the sidecar within your Service Mesh Applications"? Realized that we are "installing" two different things in the accordion sidebar, and this one might be better phrased as "Adding"

2020-04-01 16:17 UTC, merged