MAISTRA-1219 Use Maistra/istio/samples/bookinfo instead of Maistra/bookinfo
Maistra/maistra.github.io pull request #121
Opened 2020-04-17 14:04 UTC by luksa

2020-04-17 14:10 UTC, brian-avery approved these changes

2020-04-17 14:10 UTC, brian-avery commented
@neal-timpe You will need these as well.

2020-04-21 14:22 UTC, brian-avery commented on topics/docs/examples/bookinfo.adoc
> -$ oc -n ${BOOKINFO_NS} apply -f https://raw.githubusercontent.com/Maistra/bookinfo/maistra-1.1/bookinfo.yaml
Please add the following to the top of the doc (under ---)
`include::vars.adoc[]`

and `{{ .Site.Data.release.maistraBranch }}` in place of maistra-1.1

2020-04-21 14:27 UTC, luksa commented on topics/docs/examples/bookinfo.adoc
> -$ oc -n ${BOOKINFO_NS} apply -f https://raw.githubusercontent.com/Maistra/bookinfo/maistra-1.1/bookinfo.yaml
Done. Thanks.

2020-04-21 23:05 UTC, jwendell requested changes

2020-04-21 23:05 UTC, jwendell commented on topics/docs/examples/bookinfo.adoc
> +$ oc -n ${BOOKINFO_NS} apply -f https://raw.githubusercontent.com/Maistra/istio/{{ .Site.Data.release.maistraBranch }}/samples/bookinfo/platform/kube/bookinfo.yaml
Not sure what's the reason of this (can be the merge conflict?) but the preview page didn't render those variables.

2020-04-22 14:21 UTC, luksa commented on topics/docs/examples/bookinfo.adoc
> +$ oc -n ${BOOKINFO_NS} apply -f https://raw.githubusercontent.com/Maistra/istio/{{ .Site.Data.release.maistraBranch }}/samples/bookinfo/platform/kube/bookinfo.yaml
Yeah, I noticed this yesterday. It's not due to the merge conflict. For some reason Hugo doesn't replace variables in .adoc files (but it does in .html files). I tried to find the cause, but haven't figured it out yet. @brian-avery also said he'd look into it.

2020-04-22 14:32 UTC, brian-avery commented
Yeah, I'm looking into it. If you want to back out that change from here for now, I can update it to use the vars in a separate  PR.

2020-04-22 14:32 UTC, brian-avery commented
/test check-links

2020-04-22 14:53 UTC, luksa commented on topics/docs/examples/bookinfo.adoc
> +$ oc -n ${BOOKINFO_NS} apply -f https://raw.githubusercontent.com/Maistra/istio/{{ .Site.Data.release.maistraBranch }}/samples/bookinfo/platform/kube/bookinfo.yaml
OK, I've replaced this with a hardcoded version. We'll add the variable once we figure out what's wrong.

2020-04-22 14:55 UTC, brian-avery commented
The link checker will pass as soon as this merges: https://github.com/Maistra/maistra.github.io/pull/127

2020-04-22 15:14 UTC, jwendell commented on topics/docs/examples/bookinfo.adoc
> +$ oc -n ${BOOKINFO_NS} apply -f https://raw.githubusercontent.com/Maistra/istio/maistra-1.1/samples/bookinfo/platform/kube/bookinfo.yaml
For these links to work you need to backport https://github.com/Maistra/istio/pull/104 to 1.1 first, right?

2020-04-22 15:16 UTC, brian-avery commented
/test check-links

2020-04-22 15:19 UTC, luksa commented on topics/docs/examples/bookinfo.adoc
> +$ oc -n ${BOOKINFO_NS} apply -f https://raw.githubusercontent.com/Maistra/istio/maistra-1.1/samples/bookinfo/platform/kube/bookinfo.yaml
Well..  actually... they already work because at some point yesterday, I accidentally pushed directly to the maistra-1.1 branch. I still don't know when it happened, but it was probably connected to the fact that I initially opened this PR in my local maistra-1.1 branch instead of a feature branch. Oops. :)

Good thing that you've already approved https://github.com/Maistra/istio/pull/104 :)

2020-04-22 15:41 UTC, jwendell commented on topics/docs/examples/bookinfo.adoc
> +$ oc -n ${BOOKINFO_NS} apply -f https://raw.githubusercontent.com/Maistra/istio/maistra-1.1/samples/bookinfo/platform/kube/bookinfo.yaml
I thought branch protections would prevent us from making such mistakes :(

2020-04-22 15:42 UTC, jwendell approved these changes

2020-04-22 15:42 UTC, luksa commented on topics/docs/examples/bookinfo.adoc
> +$ oc -n ${BOOKINFO_NS} apply -f https://raw.githubusercontent.com/Maistra/istio/maistra-1.1/samples/bookinfo/platform/kube/bookinfo.yaml
We only prevent force-pushes.

2020-04-22 15:45 UTC, merged