[MAISTRA-1744] Route Annotations Documentation Update
Maistra/maistra.github.io pull request #158
Opened 2020-08-12 16:34 UTC by rtselizondo

Adding documentation in reference to propagating route annotations in IOR. Feature will be added from this PR https://github.com/maistra/istio/pull/158

https://issues.redhat.com/browse/MAISTRA-1744

2020-08-12 16:48 UTC, brian-avery commented on topics/docs/comparison-with-istio/ior.adoc
> +Route annotations will be propagated from the Istio gateway definition on creation only. Annotations the key name starting with `kubectl.kubernetes.io` will be ignored. This feature will allow you to
Thanks for the contribution @rtselizondo. 

Perhaps something like this might be better:

Some ACME providers require annotations in order to generate certificates. To solve this problem, Maistra ignores annotations with a key starting with `kubectl.kubernetes.io` and instead attaches them to the generated routes. Route annotations will be propagated from the Istio gateway definition on creation only.

2020-08-12 17:29 UTC, jwendell commented on topics/docs/comparison-with-istio/ior.adoc
> +Route annotations will be propagated from the Istio gateway definition on creation only. Annotations the key name starting with `kubectl.kubernetes.io` will be ignored. This feature will allow you to
I don't see a reason to mention ACME. For me it's enough to say that annotations will be copied over. This is a "generic" feature that people can take advantage for. ACME is one of those users.

2020-08-12 17:30 UTC, brian-avery commented on topics/docs/comparison-with-istio/ior.adoc
> +Route annotations will be propagated from the Istio gateway definition on creation only. Annotations the key name starting with `kubectl.kubernetes.io` will be ignored. This feature will allow you to
True.

2020-08-12 17:53 UTC, brian-avery commented
/retest

2020-08-12 17:56 UTC, brian-avery commented
That failure is being fixed in https://github.com/maistra/maistra.github.io/pull/161.

2020-08-12 17:58 UTC, brian-avery commented
/retest

2020-08-12 18:02 UTC, rtselizondo commented on topics/docs/comparison-with-istio/ior.adoc
> +Route annotations will be propagated from the Istio gateway definition on creation only. Annotations the key name starting with `kubectl.kubernetes.io` will be ignored. This feature will allow you to
@brian-avery @jwendell , Thanks for looking at this 😄 

How about this?

> Routes will be created with the same annotations as the Istio gateway definition. Annotations from `kubectl.kubernetes.io` will be ignored (for clarity / to avoid confusion / to not copy the incorrect state to the generated object). This propagation will only occur when the route is first created for each host.

I'm open to how we explain the reasoning behind the kubectl annotation being ignored. Thoughts?

2020-08-12 18:06 UTC, jwendell commented on topics/docs/comparison-with-istio/ior.adoc
> +Route annotations will be propagated from the Istio gateway definition on creation only. Annotations the key name starting with `kubectl.kubernetes.io` will be ignored. This feature will allow you to
yes, please remove this kubectl annotation explanation.

2020-08-12 18:09 UTC, rtselizondo commented on topics/docs/comparison-with-istio/ior.adoc
> +Route annotations will be propagated from the Istio gateway definition on creation only. Annotations the key name starting with `kubectl.kubernetes.io` will be ignored. This feature will allow you to
Agreed, 

> Routes will be created with the same annotations as the Istio gateway definition. Annotations from kubectl.kubernetes.io will be ignored. This propagation will only occur when the route is first created for each host.

Approved?

2020-08-12 18:10 UTC, brian-avery commented on topics/docs/comparison-with-istio/ior.adoc
> +Route annotations will be propagated from the Istio gateway definition on creation only. Annotations the key name starting with `kubectl.kubernetes.io` will be ignored. This feature will allow you to
The language there sounds better to me, but the statement refers to "This propagation will only occur..." without previously mentioning propagation occurring. What about: 

> Routes will be created with the same annotations as the Istio gateway definition. Annotations from kubectl.kubernetes.io will be ignored by Maistra and propagated to generated routes. This propagation will only occur when the route is first created for each host.

2020-08-12 18:33 UTC, rtselizondo commented on topics/docs/comparison-with-istio/ior.adoc
> +Route annotations will be propagated from the Istio gateway definition on creation only. Annotations the key name starting with `kubectl.kubernetes.io` will be ignored. This feature will allow you to
It's bit confusing to say something is ignored and used to propagate. How about we remove propagation completely ?

> Routes will be created with the same annotations as the Istio gateway definition. Annotations from `kubectl.kubernetes.io` will be ignored. This will only occur when the route is first created for each host.

2020-08-12 18:39 UTC, jwendell commented on topics/docs/comparison-with-istio/ior.adoc
> +Route annotations will be propagated from the Istio gateway definition on creation only. Annotations the key name starting with `kubectl.kubernetes.io` will be ignored. This feature will allow you to
What about:

All annotations present in the Istio gateway definition, except those starting with `kubectl.kubernetes.io` will be copied over to the newly created OpenShift route. This will only occur when the route is created.

2020-08-12 18:41 UTC, rtselizondo commented on topics/docs/comparison-with-istio/ior.adoc
> +Route annotations will be propagated from the Istio gateway definition on creation only. Annotations the key name starting with `kubectl.kubernetes.io` will be ignored. This feature will allow you to
/lgtm

2020-08-12 18:43 UTC, rtselizondo commented on topics/docs/comparison-with-istio/ior.adoc
> +Route annotations will be propagated from the Istio gateway definition on creation only. Annotations the key name starting with `kubectl.kubernetes.io` will be ignored. This feature will allow you to
I've pushed this update.

2020-08-12 18:44 UTC, brian-avery commented on topics/docs/comparison-with-istio/ior.adoc
> +Route annotations will be propagated from the Istio gateway definition on creation only. Annotations the key name starting with `kubectl.kubernetes.io` will be ignored. This feature will allow you to
Sounds good to me.

2020-08-12 18:44 UTC, brian-avery approved these changes

2020-08-12 18:49 UTC, jwendell requested changes

2020-08-12 18:49 UTC, jwendell commented on topics/docs/comparison-with-istio/ior.adoc
> +All annotations present in the Istio gateway definition, except those starting with kubectl.kubernetes.io will be copied over to the newly created OpenShift route. This will only occur when the route
missing quotes ?

2020-08-12 18:51 UTC, rtselizondo commented on topics/docs/comparison-with-istio/ior.adoc
> +All annotations present in the Istio gateway definition, except those starting with kubectl.kubernetes.io will be copied over to the newly created OpenShift route. This will only occur when the route
fixed 😄

2020-08-12 19:00 UTC, jwendell approved these changes

2020-08-12 19:02 UTC, brian-avery commented
/retest

2020-08-12 19:22 UTC, merged

2020-08-13 01:14 UTC, brian-avery commented
/cherry-pick maistra-1.1