2.0.2 docs
Maistra/maistra.github.io pull request #177
Opened 2021-03-03 16:25 UTC by brian-avery

2021-03-03 16:26 UTC, brian-avery commented on data/releases/2.0.2.yaml
> +version: 2.0.1
These values might be incorrect. The OSSM versions documentation was never updated for 2.0.2

2021-03-03 16:28 UTC, brian-avery commented
/cherrypick maistra-2.0

2021-03-03 18:23 UTC, brian-avery commented
/retest

2021-03-03 18:24 UTC, brian-avery commented
/test  maistra.github.io_check-links

2021-03-03 18:49 UTC, brian-avery commented
This PR is blocked by: https://github.com/maistra/test-infra/pull/136

2021-03-03 21:28 UTC, brian-avery commented
/retest

2021-03-03 21:28 UTC, brian-avery commented
/test maistra.github.io_check-links

2021-03-03 21:28 UTC, brian-avery commented
/test all

2021-03-11 16:23 UTC, brian-avery commented
@rcernich @knrc can you please take a look?

2021-03-11 16:32 UTC, rcernich approved these changes

2021-03-11 16:33 UTC, brian-avery commented
Thanks Rob

2021-03-15 18:11 UTC, knrc requested changes

2021-03-15 18:11 UTC, knrc commented on data/releases/2.0.2.yaml
> +kialiVersion: 1.20.3
1.24.6

2021-03-15 18:11 UTC, knrc commented on data/releases/2.0.1.yaml
> +kialiVersion: 1.20.3
1.24.5

2021-03-15 18:18 UTC, brian-avery commented on data/releases/2.0.1.yaml
> +kialiVersion: 1.20.3
Thanks. Fixed.

2021-03-15 18:21 UTC, brian-avery commented
/test check-links

2021-03-15 18:34 UTC, knrc approved these changes

2021-03-15 18:34 UTC, merged