Multitenancy notes
Maistra/maistra.github.io pull request #62
Opened 2019-07-23 20:07 UTC by brian-avery

2019-07-24 18:28 UTC, jwendell requested changes
Do we need those HTML files in this PR?

2019-07-24 18:28 UTC, jwendell commented on topics/docs/getting_started/install.adoc
> +Single tenancy is disabled by default in TP12. To enable it, set multitenant to false in your `ServicemeshControlPlane`. In order to deploy the Istio Control Plane, we need to create a custom resourc
tenancy or tenant? I'm confused with English. Can we use both deliberately?
Also, ServicemeshControlPlane -> ServiceMeshControlPlane

2019-07-24 18:28 UTC, jwendell commented on topics/docs/getting_started/install.adoc
> +Multitenancy is enabled by default in TP12. To use it, create a namespace to contain the control plane, and create the custom resource in that namespace.
tenancy or tenant? I'm confused with English. Can we use both deliberately?

Suggestion: ... create the `ServiceMeshControlPlane` custom resource in that namespace.

Also, since we are using OpenShift and targeting regular users, I'd replace all instances of namespaces with projects. But that's beyond the goals of this PR...

2019-07-24 18:38 UTC, brian-avery commented on topics/docs/getting_started/install.adoc
> +Single tenancy is disabled by default in TP12. To enable it, set multitenant to false in your `ServicemeshControlPlane`. In order to deploy the Istio Control Plane, we need to create a custom resourc
Similar words. 

Tenancy is: A habitation held or occupied by a tenant.
Tenant is: A dweller in a place; an occupant.

Could say "single tenant mode".

2019-07-24 20:18 UTC, jwendell approved these changes
LGTM. Please, use the Squashing option when merging

2019-07-25 16:10 UTC, dmitri-d commented on topics/docs/getting_started/install.adoc
> +Single tenancy is disabled by default in TP12. To enable it, set multitenant to false in your `ServicemeshControlPlane`. In order to deploy the Istio Control Plane, we need to create a custom resourc
"Single tenancy" sounds good to me.

2019-07-25 16:16 UTC, dmitri-d commented on topics/docs/getting_started/install.adoc
> +Multitenancy is enabled by default in TP12. To use it, create a namespace to contain the control plane, and create the custom resource in that namespace.
agree with @jwendell  re: using "create the ServiceMeshControlPlane" comment

2019-07-25 16:16 UTC, dmitri-d approved these changes
lgtm

2019-07-25 16:29 UTC, merged