1.0 updates
Maistra/maistra.github.io pull request #68
Opened 2019-07-31 19:18 UTC by brian-avery

2019-07-31 19:18 UTC, brian-avery commented
Fixes #67

2019-07-31 19:21 UTC, jwendell commented on config.toml
> +title = "Maistra.io -- Istio for OpenShift"
s/Istio/Service Mesh/ ?

2019-07-31 19:22 UTC, brian-avery commented on config.toml
> +title = "Maistra.io -- Istio for OpenShift"
Service Mesh for OpenShift doesn't make that much sense to me. It's a repackaging of Istio + additional functionality for OpenShift.

2019-07-31 20:19 UTC, dmitri-d commented on topics/docs/getting_started/install.adoc
> +- NOTE: Oc cluster up, OpenShift Online and OpenShift Dedicated do not work
Nit: lower-case ```oc```

2019-07-31 20:20 UTC, dmitri-d reviewed
Other than a small nit, lgtm.

2019-08-02 11:56 UTC, jwendell approved these changes

2019-08-05 13:35 UTC, brian-avery commented on config.toml
> +title = "Maistra.io -- Istio for OpenShift"
@knrc thoughts on this? Should it just be called Maistra.io?

2019-08-05 13:36 UTC, brian-avery commented on topics/docs/getting_started/install.adoc
> +- NOTE: Oc cluster up, OpenShift Online and OpenShift Dedicated do not work
@knrc Also, thoughts on language here?

2019-08-12 17:48 UTC, knrc requested changes

2019-08-12 17:48 UTC, knrc commented on config.toml
> +title = "Maistra.io -- Istio for OpenShift"
I think this wording is fine

2019-08-12 17:48 UTC, knrc commented on topics/docs/getting_started/install.adoc
> +- NOTE: Oc cluster up, OpenShift Online and OpenShift Dedicated do not work
@brian-avery Perhaps rephrase this slightly, instead of saying 'do not work' it may be better to say are 'are not supported'

2019-08-12 17:58 UTC, knrc commented on topics/docs/getting_started/install.adoc
> +- NOTE: Oc cluster up, OpenShift Online and OpenShift Dedicated do not work
Instead how about

"We no longer maintain a version of 'oc cluster up' for use with Service Mesh and we do not yet run within an OpenShift Online or OpenShift Dedicated environment"

2019-08-12 18:37 UTC, knrc approved these changes

2019-08-12 18:49 UTC, merged