[Maistra-367] Document smcp templates
Maistra/maistra.github.io pull request #74
Opened 2019-08-09 00:17 UTC by brian-avery

This is the documentation that goes along with the code changes in Maistra-367.

2019-08-09 16:04 UTC, jwendell requested changes

2019-08-09 16:04 UTC, jwendell commented on config.toml
>  weight = 1
:)

2019-08-09 16:04 UTC, jwendell commented on topics/docs/getting_started/install.adoc
> +- NOTE: Oc cluster up, OpenShift Online and OpenShift Dedicated do not work
`oc` in lower case?

2019-08-09 16:04 UTC, jwendell commented on topics/docs/getting_started/install.adoc
> +To add custom templates, create a configmap called `smcp-templates` in the istio-operator project. This configmap will contain a collection
I think that in this (community) doc we should only mention community (maistra). This avoids confusion.

2019-08-09 16:04 UTC, jwendell commented on topics/docs/getting_started/install.adoc
> +
Should we revisit this location after we decide the correct location (/usr/local/share, or /etc, or whatever)

2019-08-09 16:04 UTC, jwendell commented on topics/docs/getting_started/install.adoc
> +To create the configmap, execute the following, substituting templates-directory for a directory containing a collection
Should we have consistency on how we call it: configmap, ConfigMap, configMap, Config Map....

2019-08-09 16:04 UTC, jwendell commented on topics/docs/getting_started/install.adoc
> +```
I think it is worth to run an `ls -l` and show the output, and also probably a `cat` in some file, just to make it clear to the user about the content of a file and the contents of the directory.

2019-08-09 16:04 UTC, jwendell commented on topics/docs/getting_started/install.adoc
> +```
Also, to make the example more useful, it's probably a better idea use an example other than `default`. So, in the directory above, you could have two files, say, `development` and `production`, or, `teamA` and `teamB` and here you could reference one of those.

2019-08-09 16:17 UTC, brian-avery commented on config.toml
>  weight = 1
Oops. Looks like this snuck in from my other PR.

2019-08-09 16:18 UTC, brian-avery commented on topics/docs/getting_started/install.adoc
> +- NOTE: Oc cluster up, OpenShift Online and OpenShift Dedicated do not work
Not sure, but again, this snuck in. Let me reset the commits on this one. That said, sentences should begin with a capital letter and this isn't a command. Is it an abbreviation for something? If so, then it should be OC

2019-08-09 16:19 UTC, brian-avery commented on topics/docs/getting_started/install.adoc
> +To add custom templates, create a configmap called `smcp-templates` in the istio-operator project. This configmap will contain a collection
Pattern all along has been to discuss configuration for both OSSM and Maistra in the Maistra docs. I think it would be cleaner just to do the one, but conversation to have.

2019-08-09 17:38 UTC, dmitri-d approved these changes
lgtm

2019-08-12 13:06 UTC, dgn commented on topics/docs/getting_started/install.adoc
> +
I agree, as opposed to the `default-templates`, this is user config and should go into `/etc/`

2019-08-12 13:13 UTC, dgn commented on topics/docs/getting_started/custom-install.adoc
> +|template|Templates are used to inherit settings from another SMCP | default
I think this is a bit confusing. I'd prefer something like 

> Templates can be used to define and reuse default SMCP values across different service meshes

Possibly also mentioning that they're cluster-wide

2019-08-12 13:13 UTC, dgn commented on topics/docs/getting_started/install.adoc
> +```
+1, and maybe also overwrite a value:
```
spec:
  template: development
  istio:
    global:
      hub: myteamhub # this will override the value from the 'development' template
```

Possibly there should be even more examples for the override behaviour, e.g. maps vs keys etc.

2019-08-12 14:50 UTC, brian-avery commented on topics/docs/getting_started/install.adoc
> +```
Should probably add a note about default as well saying that admins can override it for a site-wide default config.

2019-08-12 18:54 UTC, JStickler commented on topics/docs/getting_started/install.adoc
> +- NOTE: Oc cluster up, OpenShift Online and OpenShift Dedicated do not work
My suggestion would be to rewrite the sentence to put `oc cluster up` at the end and use the font/formatting that you use to indicate a command (because technically it is one, even if you're not executing it in this sentence).

2019-08-12 18:57 UTC, JStickler commented on topics/docs/getting_started/install.adoc
> +To create the configmap, execute the following, substituting templates-directory for a directory containing a collection
Looks like Kubernetes goes with ConfigMap.

2019-08-12 20:00 UTC, brian-avery commented on topics/docs/getting_started/install.adoc
> +- NOTE: Oc cluster up, OpenShift Online and OpenShift Dedicated do not work
@JStickler Fixed in the other PR, but yeah, that solves the problem of how to capitalize it.

2019-08-12 20:01 UTC, brian-avery commented on topics/docs/getting_started/install.adoc
> +To create the configmap, execute the following, substituting templates-directory for a directory containing a collection
Fixed. Thanks

2019-08-13 01:58 UTC, brian-avery commented on topics/docs/getting_started/custom-install.adoc
> +|template|Templates are used to inherit settings from another SMCP | default
Fixed. Thanks

2019-08-13 22:38 UTC, dmitri-d commented on topics/docs/getting_started/install.adoc
> +Next, find and edit the operator deloyment in the operator cluster service version to
The doc says deployment, while the example shows editing of the csv.

2019-08-13 22:40 UTC, dmitri-d commented on topics/docs/getting_started/install.adoc
> +Next, find and edit the operator deloyment in the operator cluster service version to
Ugh, the wording is fine, nm me.

2019-08-13 23:16 UTC, jwendell approved these changes
Please squash the commits before merging.

2019-08-14 17:28 UTC, merged