Documented known deprecated fields
Maistra/maistra.github.io pull request #75
Opened 2019-08-14 23:18 UTC by brian-avery

2019-08-15 14:23 UTC, JStickler commented on topics/docs/troubleshooting/deprecated-fields.adoc
> +and will be picked up in Maisra/OpenShift Service Mesh at a later date.
By "picked up" do you mean removed?

2019-08-15 15:03 UTC, brian-avery commented on topics/docs/troubleshooting/deprecated-fields.adoc
> +and will be picked up in Maisra/OpenShift Service Mesh at a later date.
yeah, that's probably better. Was thinking the linked issue would be picked up.

2019-08-19 14:21 UTC, jwendell requested changes

2019-08-19 14:21 UTC, jwendell commented on topics/docs/troubleshooting/deprecated-fields.adoc
> +Please find a list of known deprecated fields below. These are addressed in link:https://github.com/istio/istio/pull/13182[Istio 1.2]
It would be useful to have an example of a full message as it appears on proxy logs

2019-08-19 14:21 UTC, jwendell commented on topics/docs/troubleshooting/deprecated-fields.adoc
> +and will be removed when Maistra/OpenShift Service Mesh are upgraded to 1.2.
1.2 or later

2019-08-20 11:21 UTC, dgn commented on topics/docs/troubleshooting/deprecated-fields.adoc
> +There are several messages concerning deprecated fields that you may see in the Istio logs that can be safely ignored.
I think this should mention that the messages can only be seen in `istio-proxy`/`envoy` logs

2019-08-26 17:26 UTC, jwendell approved these changes

2019-08-27 07:27 UTC, dgn approved these changes

2019-08-27 07:30 UTC, merged