Update Multitenancy Document to state current status
Maistra/maistra.github.io pull request #76
Opened 2019-08-16 17:45 UTC by brian-avery

2019-08-16 18:16 UTC, rcernich requested changes

2019-08-16 18:16 UTC, rcernich commented on topics/docs/comparison_with_community/multitenancy.adoc
> +* ServiceMeshPolicy replaces MeshPolicy and ClusterRbacConfig with ServicemeshRbacConfig
I'd split this into two:

* ServiceMeshPolicy replaces MeshPolicy and should be located within the control plane's namespace (e.g. istio-system)
* ServiceMeshRbacConfig replaces ClusterRbacConfig and should be located within the control plane's namespace

I'd also add:
* When the OpenShift cluster is configured to use ovs-networkpolicy, NetworkPolicy resources are added to every project in the mesh (i.e. those in `ServiceMeshMemberRoll.spec.members`) to ensure network connectivity between projects in the mesh.  (Note, if you require ingress to mesh projects from project outside the mesh, you will need to define addition NetworkPolicy rules to allow that traffic.)
* When the OpenShift cluster is configured to use ovs-multitenant, mesh project networks into the control plane project's network (similar to `oc adm pod-network join-projects --to istio-system project1 project2`) to ensure network connectivity between projects in the mesh.

2019-08-16 19:36 UTC, JStickler commented on topics/docs/comparison_with_community/multitenancy.adoc
> +* ServiceMeshPolicy replaces MeshPolicy and ClusterRbacConfig with ServicemeshRbacConfig
ovs-multitenant?  Could we spell out all the acronyms somewhere in the text to help people who don't know them figure out what you're talking about.  (See also RBAC above around line 16, we should spell out Rules Based Access Control (RBAC) to help users understand what you mean.)

2019-08-16 20:54 UTC, rcernich commented on topics/docs/comparison_with_community/multitenancy.adoc
> +* ServiceMeshPolicy replaces MeshPolicy and ClusterRbacConfig with ServicemeshRbacConfig
Those used to be network configuration types.  It appears for 4.1 it should say:

When cluster network is configured to use SDN mode (NetworkPolicy|Multitenant)...

OpenShift network configuration is documented here: https://docs.openshift.com/container-platform/4.1/networking/cluster-network-operator.html#nw-operator-cr_cluster-network-operator

2019-08-16 20:56 UTC, rcernich commented on topics/docs/comparison_with_community/multitenancy.adoc
> +* ServiceMeshPolicy replaces MeshPolicy and ClusterRbacConfig with ServicemeshRbacConfig
For the most part, users shouldn't care, however there are cases when using NetworkPolicy where they might get unexpected behavior, specifically other namespaces not being able to access mesh namespaces (default when using NetworkPolicy is to allow all traffic, but that changes as soon as any NetworkPolicy resource is added to a namespace).

2019-08-20 19:28 UTC, jwendell approved these changes
LGTM with the suggestions from Rob applied. Also made a minor comment about IOR, which could be done now or by the other issue @dmitri-d is working on.

2019-08-20 19:28 UTC, jwendell commented on topics/docs/comparison_with_community/multitenancy.adoc
>  * The *IOR* component has not yet been updated to work with Multi-Tenancy so should be disabled within the *ServiceMeshControlPlane* instance.
This should be removed as well, which leaves no items in this section. We have no known issues \o/

2019-08-20 19:46 UTC, brian-avery commented on topics/docs/comparison_with_community/multitenancy.adoc
>  * The *IOR* component has not yet been updated to work with Multi-Tenancy so should be disabled within the *ServiceMeshControlPlane* instance.
I'll remove this one, but I think the rest of the IOR changes should be removed as part of Dmitri's PR. That way we can find and revert everything when it gets reimplemented.

2019-08-20 20:00 UTC, brian-avery commented on topics/docs/comparison_with_community/multitenancy.adoc
> +* ServiceMeshPolicy replaces MeshPolicy and ClusterRbacConfig with ServicemeshRbacConfig
Created Maistra-816 to add documentation on how to use ServiceMeshPolicy and ServiceMeshRbacConfig. I think we really need a doc on them rather than overloading a list of features with install instructions. Will add those to here for now, but that's more for @geekspertise reference than actually being something I think users will find.

2019-08-20 20:10 UTC, brian-avery commented on topics/docs/comparison_with_community/multitenancy.adoc
> +* ServiceMeshPolicy replaces MeshPolicy and ClusterRbacConfig with ServicemeshRbacConfig
Created Maistra-816 to add documentation about networking types. Similar idea to above, I think those need to be promoted to documentation that people will read when installing/using OSSM/Maistra.

2019-08-22 15:39 UTC, rcernich requested changes

2019-08-22 15:39 UTC, rcernich commented on topics/docs/comparison_with_community/multitenancy.adoc
> +* ClusterRbacConfig replaces ServicemeshRbacConfig for configuration of control-plane-wide role based access control. This must be created in the same namespace as teh control plane.
These are reversed, s/b, `ServiceMeshRbacConfig replaces...`

2019-08-22 15:39 UTC, rcernich commented on topics/docs/comparison_with_community/multitenancy.adoc
> +* When the cluster network is configured to use SDN mode (network policy or multitenant), NetworkPolicy resources are added to every project in the mesh to ensure network
Remove multitenant.

2019-08-22 15:39 UTC, rcernich commented on topics/docs/comparison_with_community/multitenancy.adoc
> +connectivity between projects. External traffic must be listed in the network policy in order to be able to communicate with pods in the mesh.
s/b, `If non-mesh namespaces require network access to the mesh (other than through the ingress gateway), users will need to create NetworkPolicy resources to allow ingress to mesh namespaces from non-mesh namespaces.`

2019-08-28 09:05 UTC, dgn commented on topics/docs/comparison_with_community/multitenancy.adoc
> +* ClusterRbacConfig replaces ServicemeshRbacConfig for configuration of control-plane-wide role based access control. This must be created in the same namespace as teh control plane.
This now duplicates another chapter I added in https://github.com/Maistra/maistra.github.io/pull/82 - I think that's not necessarily a problem, though

2019-08-28 17:55 UTC, brian-avery commented
Something weird going on in this PR. Subsuming it as part of:
https://github.com/Maistra/maistra.github.io/pull/84

2019-08-28 17:55 UTC, closed without merging