[MAISTRA-787] Update kiali custom installation doc
Maistra/maistra.github.io pull request #77
Opened 2019-08-20 13:35 UTC by jwendell

2019-08-20 14:15 UTC, brian-avery approved these changes

2019-08-21 19:14 UTC, dmitri-d approved these changes

2019-08-22 15:50 UTC, rcernich commented on topics/docs/getting_started/custom-install.adoc
> +|user|This is the username used to access the Kiali console. Note that this is not related to any account on OpenShift. | none
Will kiali even work with separate user/pwd?  I'm not sure how permissions work if this is specified, as kiali uses the user's creds to determine what it can access.  I'm not sure how it governs access for kiali user.  Also, for this to work, the user must also specify `dashboard.secretName` (although I'm not sure it supports any mode other than oauth).  I recommend all this dashboard stuff be removed (or have the kiali team document what settings are available in maistra).

2019-08-23 18:46 UTC, jwendell commented on topics/docs/getting_started/custom-install.adoc
> +|user|This is the username used to access the Kiali console. Note that this is not related to any account on OpenShift. | none
@rcernich updated accordingly.

2019-08-23 18:50 UTC, dmitri-d commented on topics/docs/getting_started/custom-install.adoc
> +For more information on those dashboard exported options above, check the link:https://github.com/kiali/kiali/blob/v1.0.5/operator/deploy/kiali/kiali_cr.yaml[Kiali reference].
nit: Not sure if I interpreted it correctly, but it sounded a bit verbose to me. Perhaps something like: "the dashboard options above"?

2019-08-23 18:50 UTC, dmitri-d approved these changes
small nit, but lgtm.

2019-08-23 18:52 UTC, jwendell commented on topics/docs/getting_started/custom-install.adoc
> +For more information on those dashboard exported options above, check the link:https://github.com/kiali/kiali/blob/v1.0.5/operator/deploy/kiali/kiali_cr.yaml[Kiali reference].
thanks, updated.

2019-08-23 18:55 UTC, brian-avery commented on topics/docs/getting_started/custom-install.adoc
> +For more information on those dashboard exported options above, check the link:https://github.com/kiali/kiali/blob/v1.0.5/operator/deploy/kiali/kiali_cr.yaml[Kiali reference].
Can we reference Kiali like this? I don't think we support all of their installation options. Think you're skipping the middle man of our operator.

2019-08-23 18:57 UTC, brian-avery commented on topics/docs/getting_started/custom-install.adoc
> +For more information on those dashboard exported options above, check the link:https://github.com/kiali/kiali/blob/v1.0.5/operator/deploy/kiali/kiali_cr.yaml[Kiali reference].
The only options we support are those listed here: https://github.com/Maistra/istio-operator/blob/maistra-1.0/helm/istio/charts/kiali/templates/kiali-cr.yaml

2019-08-23 18:59 UTC, jwendell commented on topics/docs/getting_started/custom-install.adoc
> +For more information on those dashboard exported options above, check the link:https://github.com/kiali/kiali/blob/v1.0.5/operator/deploy/kiali/kiali_cr.yaml[Kiali reference].
Not sure. I wanted to say that: "We support the options above. If you want more information on those, refer to the proper doc." I don't feel it's our job to provided detailed documentation - potentially duplicating content from their doc - for kiali options.

We have at the end of this page: "For further options..." which I think has the same purpose, no?

2019-08-23 18:59 UTC, brian-avery requested changes

2019-08-23 18:59 UTC, brian-avery commented on topics/docs/getting_started/custom-install.adoc
> +For more information on the dashboard options above, check the link:https://github.com/kiali/kiali/blob/v1.0.5/operator/deploy/kiali/kiali_cr.yaml[Kiali reference].
Don't think this is valid. The only options we support are listed here: https://github.com/Maistra/istio-operator/blob/maistra-1.0/helm/istio/charts/kiali/templates/kiali-cr.yaml Probably shouldn't be linking to documentation on stuff that may or may not work.

2019-08-23 19:06 UTC, jwendell commented on topics/docs/getting_started/custom-install.adoc
> +For more information on the dashboard options above, check the link:https://github.com/kiali/kiali/blob/v1.0.5/operator/deploy/kiali/kiali_cr.yaml[Kiali reference].
ok, removed that part.

2019-08-23 19:07 UTC, brian-avery commented on topics/docs/getting_started/custom-install.adoc
> +For more information on those dashboard exported options above, check the link:https://github.com/kiali/kiali/blob/v1.0.5/operator/deploy/kiali/kiali_cr.yaml[Kiali reference].
The difference between that and us is we are an Istio derivative and support all of the upstream Helm installation options. Kiali is a separate product and we only support a subset of their install options. We should document the ones that we support. We're also generating a ServiceMeshControlPlane configuration and not a Kiali configuration, so these are actually two different things.

2019-08-23 19:09 UTC, brian-avery commented on topics/docs/getting_started/custom-install.adoc
> +For more information on those dashboard exported options above, check the link:https://github.com/kiali/kiali/blob/v1.0.5/operator/deploy/kiali/kiali_cr.yaml[Kiali reference].
On top of that, some of the fields we actually change to generate new fields. I.e. image.

2019-08-23 19:11 UTC, brian-avery commented on topics/docs/getting_started/custom-install.adoc
> +If you intend to use a custom image, you must override all three values of hub, image and tag above.
Might be overloading this PR a bit, but can you please do the same for Jaeger?

2019-08-23 19:24 UTC, brian-avery approved these changes

2019-08-23 20:55 UTC, merged