[maistra-869] [maistra-866] Update to Kiali docs
Maistra/maistra.github.io pull request #95
Opened 2019-09-03 13:31 UTC by brian-avery

2019-09-03 13:57 UTC, jwendell requested changes
It seems you are making use of the istio-tutorial example to show how to use kiali. Can you make that explicit, i.e., saying that this is an example and link to it?

While reading it, I was expecting that this istio-tutorial namespace existed beforehand.

2019-09-03 13:57 UTC, jwendell commented on topics/docs/monitoring_and_tracing/kiali.adoc
>  image::kiali_login.png[]
This image is broken.

2019-09-03 13:57 UTC, jwendell commented on topics/docs/monitoring_and_tracing/kiali.adoc
> +install the link:{{< ref "operator-installation.adoc" >}}[operator] update your link:{{< ref "controlplane.adoc" >}}[SMCP] before continuing.
This sentence is confusing to me. Missing any punctuation, or an `and`?

2019-09-03 13:57 UTC, jwendell commented on topics/docs/monitoring_and_tracing/kiali.adoc
> +export INGRESS_GATEWAY=$(oc get route -n <controlplane-namespace> istio-ingressgateway -o 'jsonpath={.spec.host}')
Missing `$`?

2019-09-03 13:57 UTC, jwendell commented on topics/docs/monitoring_and_tracing/kiali.adoc
> +xdg-open https://$(oc get route -n <controlplane-namespace> kiali -o 'jsonpath={.spec.host}')
Missing `$`?

2019-09-03 13:57 UTC, jwendell commented on topics/docs/monitoring_and_tracing/kiali.adoc
> +* `Namespace`: `istio-tutorial`
Does this namespace exist beforehand?

2019-09-04 14:42 UTC, jwendell reviewed
You seem to be using only two images, not need to add 7 to this pr, right?

2019-09-04 14:44 UTC, dgn approved these changes
Looks good except for two minor things

2019-09-04 14:44 UTC, dgn commented on topics/docs/monitoring_and_tracing/kiali.adoc
> +script generating load. The traffic will flow from the Service Mesh `ingress
I think the first sentence in this paragraph is a bit convoluted. I would either leave out the "generating load" at the end or rewrite to "...showing traffic that is being generated by the script we ran above" or similar

2019-09-04 14:44 UTC, dgn commented on topics/docs/monitoring_and_tracing/kiali.adoc
> +`detials`. The request percentage will show 100% on every edge
typo details

2019-09-04 14:49 UTC, brian-avery commented on topics/docs/monitoring_and_tracing/kiali.adoc
> +script generating load. The traffic will flow from the Service Mesh `ingress
Thanks. Fixed.

2019-09-04 14:49 UTC, brian-avery commented on topics/docs/monitoring_and_tracing/kiali.adoc
> +`detials`. The request percentage will show 100% on every edge
Thanks. Fixed.

2019-09-04 14:52 UTC, brian-avery commented
This is part 1 of the Kiali docs. Part two will include the rest of the Kiali tutorial and be added later.

2019-09-04 15:44 UTC, jwendell approved these changes

2019-09-04 16:03 UTC, merged